using UnityEngine;

public class EliminadorDeEnemigos : MonoBehaviour
{
    public float tiempoDestruccion = 2f; // Tiempo antes de destruir el objeto
    public Transform camaraTransform; // Referencia a la c치mara

    void Start()
    {
        if (camaraTransform == null)
        {
            Debug.LogError("Referencia a la c치mara no asignada en el Inspector");
        }
    }

    void Update()
    {
        if (camaraTransform != null)
        {
            // Mover el eliminador de enemigos a la posici칩n de la c치mara
            transform.position = new Vector3(camaraTransform.position.x, transform.position.y, transform.position.z);
        }
    }

    void OnCollisionEnter2D(Collision2D collision)
    {
        if (collision.collider.CompareTag("Enemigo"))
        {
            collision.gameObject.SetActive(false);
            Destroy(collision.gameObject, tiempoDestruccion);
        }
    }
}
